# config_cancerfnd.yaml

# --- General Project Settings ---
project_name: "CancerFoundation_NB_Dataset3_Analysis"
random_seed: 42

# --- Input Data ---
paths:
  adata_input: "resources/embeddings/midpoint_sn_sn_3000.h5ad"
  model_dir: "no_model_given" # Assumed path - UPDATE if different

# --- Output Paths ---
output_paths:
  # Where to save the anndata with the CancerFoundation embedding
  adata_embedded_dir: "resources/embeddings/"
  adata_embedded_filename: "midpoint_sn_sn_3000.h5ad"

  # Where to save the final anndata with clustering, etc.
  adata_clustered_dir: "results/clustered_data/"
  adata_clustered_filename: "SSN(Train)_to_SN(Test)_3000HVG_CellState_X_scGPT_ipca_cluster.h5ad"

  # General output directories
  scanpy_plots_output: "concat/results/scanpy_plots/"
  autosave_plots_output: "concat/results/autosaved_plots/"
  evaluation_plots_output: "concat/results/evaluation_plots/"
  interpretability_output_dir: "concat/results/interpretability/"
  benchmarking_output_dir: "concat/results/scib_benchmark/"

# --- Data Keys ---
data_keys:
  # Key for the embedding generated by CancerFoundation
  embedding_key_model: "iPCA_scGPT"
  # Ground truth annotation for clustering evaluation (needs to exist in adata.obs)
  # Check your specific AnnData file for the correct key (e.g., 'cell_state', 'cell_type_fine')
  ground_truth_key: "cell_state" 
  # Batch key for visualization and scIB
  batch_key: "donor_id" # "donor_id" # "donor_id" when using sn_tumor cells otherwise "Sample"
  # Timepoint key for interpretability analysis
  timepoint_key: "Stage_Code" # DX, PTX
  # Value representing the "pre-treatment" or baseline state in timepoint_key
  timepoint_pre: "DX"
  # Value representing the "post-treatment" state in timepoint_key
  timepoint_post: "PTX"

# --- Embedding Generation (CancerFoundation) ---
embedding:
  # If True, force regeneration even if output file exists
  force_regenerate: False
  # Parameters for the embed function (adjust if needed)
  batch_size: 256
  # If the model expects a specific layer from input AnnData (e.g., 'X' or 'counts')
  input_layer: null # null uses adata.X

# --- Preprocessing for Downstream Analysis ---
preprocessing:
  # Number of neighbors for UMAP and Leiden/Louvain
  n_neighbors: 15
  # PCA components if needed for comparison or baseline
  n_pca_components: 50

# --- Clustering Algorithms ---
clustering:
  use_gmm: True
  use_leiden: True
  use_louvain: True
  use_kmeans: True # Optional: Can use GMM's optimal k

  # GMM parameters
  gmm:
    covariance_type: 'diag' # 'full', 'tied', 'diag', 'spherical'
    n_components_min: 2
    n_components_max: 15 # Adjust based on expected complexity
    n_init: 15

  # KMeans parameters (n_clusters set dynamically if GMM is used)
  kmeans:
    n_init: 15

  # Leiden parameters
  leiden:
    resolution: 1.0

  # Louvain parameters
  louvain:
    resolution: 1.0
  # List of cluster keys to evaluate/visualize
  clustering_keys_to_analyze:
    - 'leiden'
    - 'louvain'
    - 'gmm_cluster'
    - 'kmeans'
    # Add 'gmm_cluster' and 'kmeans' if used and desired in evaluation plots

# --- Visualization ---
visualization:
  # Embedding basis for plotting (usually UMAP based on the model embedding)
  embedding_basis: "X_umap_scGPT" # Will be created based on embedding_key_model
  figure_dpi: 300
  # Color palettes or specific settings if needed

# --- Evaluation ---
evaluation:
  # Metrics to calculate against ground_truth_key
  metrics:
    - 'ARI'
    - 'NMI'
    - 'Homogeneity'
    - 'Completeness'
    - 'V-Measure'
    - 'Silhouette' # Silhouette score on the model embedding

# --- Interpretability Analysis ---
interpretability:
  # Perform correlation of latent dimensions with timepoint_key
  correlate_dims_with_timepoint: True
  # Number of top correlated dimensions to report
  n_top_dims: 5
  # Perform DEG analysis between high/low scores of top dims (requires Scanpy tools)
  perform_deg_analysis: True # Set to False to skip DEG/Enrichment
  # Number of top genes to report per dimension (for DEG)
  n_top_genes_deg: 50
  # Log fold change threshold for DEG
  deg_lfc_threshold: 0.25
  # Adjusted p-value threshold for DEG
  deg_pval_threshold: 0.05
  # Perform pathway enrichment (requires gseapy and gene sets)
  perform_pathway_enrichment: True # Set to False to skip Enrichment
  # Organism for gseapy (e.g., "human", "mouse")
  gsea_organism: "human"
  # Max size of gene sets for GSEA
  gsea_max_size: 500


# --- scIB Benchmark ---
benchmarking:
  # Run the scIB benchmark?
  run_benchmark: True
  # Embeddings to include in the benchmark
  embedding_keys:
    # Must include the main model embedding
    - "iPCA_scGPT"
    - "X_umap_scGPT"
    - "X_pca_scGPT"
    # Add others for comparison if available/calculated (e.g., PCA)
    # - "X_harmony"
  # Use Leiden clustering labels for NMI/ARI calculation within scIB Bio Conservation
  bio_conservation_leiden: True
  # Use Kmeans clustering labels for NMI/ARI calculation within scIB Bio Conservation
  bio_conservation_kmeans: False # Often less reliable than Leiden
  # Include PCR comparison in Batch Correction score
  batch_correction_pcr: True
  # Number of parallel jobs for scIB
  n_jobs: 1